### ISSUE TITLE
how to fix "ReferenceError: options is not defined"?

### ISSUE THREAD

**Issue by luckypoem** [marijnh/blog#2]
hi.

as3:~/heckle-by-marijnh# node heckle.js

/root/heckle-by-marijnh/node_modules/marked/lib/marked.js:1113
    throw e;
          ^
ReferenceError: options is not defined
Please report this to https://github.com/chjj/marked.
    at Object.exports.runMode (/root/heckle-by-marijnh/node_modules/codemirror/addon/runmode/runmode.node.js:104:44)
    at Object.highlightCode [as highlight](/root/heckle-by-marijnh/heckle.js:19:16)
    at Parser.tok (/root/heckle-by-marijnh/node_modules/marked/lib/marked.js:858:33)
    at Parser.parse (/root/heckle-by-marijnh/node_modules/marked/lib/marked.js:797:17)
    at Function.Parser.parse (/root/heckle-by-marijnh/node_modules/marked/lib/marked.js:784:17)
    at marked (/root/heckle-by-marijnh/node_modules/marked/lib/marked.js:1105:19)
    at /root/heckle-by-marijnh/heckle.js:55:22
    at Array.forEach (native)
    at readPosts (/root/heckle-by-marijnh/heckle.js:45:29)
    at generate (/root/heckle-by-marijnh/heckle.js:123:38)
as3:~/heckle-by-marijnh#

**Comment by colbyrussell** [comment]
I can't reproduce this error.
